### ISSUE TITLE
Cannot download geopandas

### ISSUE THREAD

**Issue by Kristine123** [Kristianuruplarsen/sdseml_online_exercises#119]
Hi 
Don't know if this is the right place to raise the issue but I have a lot of trouble downloading geopandas. 

![Cannot install geopandas](https://user-images.githubusercontent.com/53855403/78062326-d091fc80-738e-11ea-940b-d7bfa84ae293.JPG)

![Cannot install geopandas 2](https://user-images.githubusercontent.com/53855403/78062466-00410480-738f-11ea-8262-1d2d358aeccc.JPG)

This is the process after 6 hours, yesterday I tried to let it run overnight without getting any further. Should I give up on my computer or is there something to do about it?

Thanks in advance

Br Kristine

**Comment by kristianolesenlarsen** [comment]
@Kristine123 

The error is saying that "the environment is inconsistent". All software comes in versions/releases (i.e. as you can see in your error curl is version 7.63.0), and have dependencies on specific versions of ofther software. The point of conda is to keep track of these version constraints to ensure that you always have compatible versions of all packages installed.

This compatibility can be broken in a number of ways. Most commonly `pip` and `conda` don't get along after installing some packages with pip and others with conda.

First try to run these two commands in your cmd and see if one of them fixes it
```
conda update --all
conda update --all --force
```
If they dont solve it try
```
conda install anaconda
```
If this doesn't work either, try 
```
conda install package_name
```
where `package_name` is one of the inconsistent packages (you might need to try them all). If all else fails, uninstall anaconda completely and reinstall.
