### ISSUE TITLE
Cannot access the Shapely module

### ISSUE THREAD

**Issue by Kristine123** [Kristianuruplarsen/sdseml_online_exercises#150]
Hi 

I cannot access the shapely module.  I have Shapely and GEOS installed and tried to access different attributes in the package all unsuccessfully with the message "module not found".

Br Kristine

**Comment by kristianolesenlarsen** [comment]
Can you share the code that is causing you problems along with the error it produces?

**Comment by Kristine123** [comment]
This is the error code:
`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-8dffbf481ce8> in <module>
----> 1 from shapely.geometry import Polygon

~\Anaconda3\lib\site-packages\shapely\geometry\__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~\Anaconda3\lib\site-packages\shapely\geometry\base.py in <module>
     16 
     17 from shapely.affinity import affine_transform
---> 18 from shapely.coords import CoordinateSequence
     19 from shapely.errors import WKBReadingError, WKTReadingError
     20 from shapely.geos import WKBWriter, WKTWriter

~\Anaconda3\lib\site-packages\shapely\coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

~\Anaconda3\lib\site-packages\shapely\geos.py in <module>
    143     if os.getenv('CONDA_PREFIX', ''):
    144         # conda package.
--> 145         _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
    146     else:
    147         try:

~\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354             """
    355             if name and name.endswith(")") and ".a(" in name:
--> 356                 mode |= ( _os.RTLD_MEMBER | _os.RTLD_NOW )
    357 
    358         class _FuncPtr(_CFuncPtr):

OSError: [WinError 126] Det angivne modul blev ikke fundet`

It says "Shapely was successfully installed" via pip in my promt. I tried uninstalling and installing again via different paths. 

Thx!

**Comment by Kristine123** [comment]
Just trying to access shapely:
`from shapely.geometry import Polygon`

**Comment by kristianolesenlarsen** [comment]
Geopandas and shapely have non-python dependencies which pip will not install. Try 
```
pip uninstall shapely
pip uninstall geopandas
```
and then 
```
conda install geopandas
```
possibly also
```
conda install -c conda-forge shapely 
```

**Comment by Kristine123** [comment]
Hi 
Thx for the help! 
I get this error in both cases:
<img width="551" alt="conda problems" src="https://user-images.githubusercontent.com/53855403/78362321-31514d00-75ba-11ea-8443-db6b31a78201.PNG">
Br

**Comment by Kristine123** [comment]
<img width="410" alt="sources2 5882" src="https://user-images.githubusercontent.com/53855403/78363234-b5f09b00-75bb-11ea-9da1-de2129a0e539.PNG">

**Comment by kristianolesenlarsen** [comment]
What happens if you run 
```
conda config --remove channels conda-forg
```
(can you show the result of `conda config --show channels` again after doing this?) and then try 
```
conda install geopandas
```
once more?

**Comment by Kristine123** [comment]
This is the channels and the installation of geopandas that has been running for about an hour:
<img width="864" alt="status 5884" src="https://user-images.githubusercontent.com/53855403/78368637-37e4c200-75c4-11ea-9005-53d89d4dd023.PNG">

**Comment by kristianolesenlarsen** [comment]
Did you do the steps in https://github.com/Kristianuruplarsen/sdseml_online_exercises/issues/119 ?

You might be better off with a clean install of anaconda, that is probably faster than trying to fix the environment.

**Comment by Kristine123** [comment]
I ended up installing anaconda "fresh" on a pretty new computer that didn't have anaconda before. So it should already be a pretty "clean" install? But I will stop the installation and try to go through the steps again!
thx!
