### ISSUE TITLE
Exercise set 5, problem 1: simulate data

### ISSUE THREAD

**Issue by SimonLiljaN** [Kristianuruplarsen/sdseml_online_exercises#2]
Hey, 

I'm struggling with data generating process. 
Especially with generating tau. I'm not even a hundred percent sure about how to read the statement given. When D=0, should the statement then include the first observation of the 0th feature of X for each tau or does it have to iterate through the 10.000 observations of the 0th feature of X? 

I hope my question makes sense. :)

**Comment by kristianolesenlarsen** [comment]
If you havent already seen, this question is already part of the writeup [here](https://github.com/Kristianuruplarsen/sdseml_online_exercises/blob/master/TA_EXAMPLE_FOLDER/exercise_4/writeup.pdf). 

Think of `D` as a randomly assigned dummy variable (size N_SAMPLES). `D` governs which "treatment effect equation" determines Tau. 

If D = 0 the treatment effect is given by the logistic equation, where X0 is, indeed, the first column/feature of X. On top of this equation, some noise (nu) also enters in this case.

If D = 1 the treatment effect is pure noise, given by nu. 

You can achieve this two-case thing by multiplying the logistic function by (1-D) (effectively multiplying by 0 whenever D=1).

I hope this makes sense!

**Comment by SimonLiljaN** [comment]
Thanks Kristian, I hadn't seen that it was a part of the writeup.
