### ISSUE TITLE
double_edge_swap() not defined for directed graphs.

### ISSUE THREAD

**Issue by emilcphu** [Kristianuruplarsen/sdseml_online_exercises#291]
Hi Kristian,

I am working on ex 10.1.3 in which we are told to carry out nx.double_edge_swap() on the facebook wallpost data from ex 9. Recall that this network is a directed network.

When I try to do so, nx tells me "double_edge_swap() not defined for directed graphs". 

How do you recommend to overcome this issue? Should we force the network to be undirected or use a edge_swap method which is robust to directed networks? (or perhaps a third possibility).

Here is the code example I try to run when I receive the error:

```
## Load data
data = pd.read_csv(
    "facebook-wall.txt.gz",
    delimiter="\t",
    header=None,
    names=['user1', 'user2', 'timestamp']
)


# create network
lag_days = 7
G        = load_fb_wall_data(data,lag_days=lag_days)

## Calculate average local cluster coefs (alcc) with weights
G_ALCC  = nx.average_clustering(G)
print(f'The ALCC of Facebook Wall posts within the past {lag_days} days is: {G_ALCC}')

## Iterations with double swaps
n_iter        = 1000
nswap       = 100
ALLC_values = []
for i in range(n_iter):
    G_tmp = G.copy()
    G_tmp = nx.double_edge_swap(G_tmp,nswap=nswap,seed=seed)
    G_tmp_ALLC = nx.average_clustering(G_tmp)
    ALLC_values.append(G_tmp_ALLC)
print(f'The average ALCC of Facebook Wall posts within the past {lag_days} days over {n_iter} iterations with double_edge_swap is: {np.mean(ALLC_values)}')
```

**Comment by kristianolesenlarsen** [comment]
I suggest you simply construct the network as an undirected graph. Clustering measures in directed graphs quickly become difficult to interpret anyways.

**Comment by emilcphu** [comment]
Roger that !
