### ISSUE TITLE
Further information about exam and interest in Facebook group for exam?

### ISSUE THREAD

**Issue by ghost** [Kristianuruplarsen/sdseml_online_exercises#306]
I was wondering if it was possible to receive a description of what to expect at the exam, or perhaps an example exam.
Furthermore, the exam description at kurser.ku.dk notes that the exam is an "individuel take-home assignment. The students are allowed to communicate about the given problem-set but must work on, write and upload the assignment answer individually. Be aware that the plagiarism rules must be complied. The exam assignment is given in English and must be answered in English." Thus, I was wondering if anyone was interested in creating a Facebook group for us in preparation for the exam. I know Github and Absalon are great and all, but perhaps the familiarity of Facebook would result in faster communication. Any thoughts?

This is a cross-post from Absalon discussion to reach as many students as possible.

**Comment by Kristine123** [comment]
Further information about the exam and a facebook group sounds good :)

**Comment by ghost** [comment]
I have created a group titled "SDS: Econometrics and Machine Learning" - if you, or anyone for that matter, search for it on Facebook, you can join the group :)
