### ISSUE TITLE
Exercise 4 and causal tree

### ISSUE THREAD

**Issue by PhilipChristiansen1** [Kristianuruplarsen/sdseml_online_exercises#447]
Hi Kristian,

I've been working through your great writeups the last couple of days. Thanks for those!

I wanted to ask, if there are solutions to exercise 4 available. I can neither see them in your folder nor in the official course folder. Am I blind or are there no solutions to this set?

Best,
Philip

**Comment by kristianolesenlarsen** [comment]
I must have forgotten to push it. It should be there now.
