### ISSUE TITLE
issue Ex 12.1.6

### ISSUE THREAD

**Issue by s-honore** [Kristianuruplarsen/sdseml_online_exercises#454]
Hi Kristian, 

I am a bit confused about ex 12.1.6. It seems like it is the same as in 12.1.5. Could you perhaps help me understand the difference in the two models? 

best 
Sebastian

**Comment by kristianolesenlarsen** [comment]
Sorry for the late response. It is a copy-paste error in the exercises. The writeup should contain a discussion of how to solve the two questions now.
