### ISSUE TITLE
Ex 6.1.2: alpha_0 or pi_0?

### ISSUE THREAD

**Issue by emilcphu** [Kristianuruplarsen/sdseml_online_exercises#46]
Hi Kristian,

You tell us to estimate an OLS using the treatment variable and a constant. The coef for the constant is defined as pi_0 in your equation. However, in the question text you ask is to evaluate the difference between alpha_0 and pi_1. Can you clarify whether it is a typo ? (that is, did you mean the difference between pi_0 and pi_1) -- or should we use the alpha_0 values generated in the simulate() funtion? .. It makes a lot better sense if it is the alphas generated in the simulation funtion  ^^

**Comment by kristianolesenlarsen** [comment]
Hi!
For once, i don't think i have made a type. You should store the "simulated" alpha_0 and the coefficient on d_i (pi_1). The graph you end up with is then a histogram over the 1000 simulations, showing the difference between the _true_ effect of d_i on y_i and the _estimated_ effect. pi_0 is of no further interest to us.

_I just saw that I have used pi for regression parameters in the exercise set, but beta in the writeup. I hope this doesn't cause additional confusion._

**Comment by emilcphu** [comment]
Thanks for the quick answer. It made a lot more sense once we got the IV-part.
