### ISSUE TITLE
Ex #6 Parameter names

### ISSUE THREAD

**Issue by signehaahr** [Kristianuruplarsen/sdseml_online_exercises#48]
Hej Kristian,

Jeg sidder lige nu og laver exercise set 6, og jeg er en smule forvirret over parametrene i opgavebeskrivelsen vs. i første kodebid.

I opgavebeskrivelsen står der:

d = z @ delta + x @ gamma + u
y = alpha * d + x @ beta + nu

I koden er det:

d = z @ Pi + x @ gamma + nu
y = alpha * d + x @ delta + u

Jeg er nu nået til opgave 6.1.4, hvor jeg skal bruge delta_0, og jeg kan ikke helt finde ud af, hvilken parameter jeg skal bruge. Jeg håber, at mit spørgsmål giver mening!

Mvh.
Signe

**Comment by kristianolesenlarsen** [comment]
For the english speakers: this question asks about inconsistencies between the variable names used in the opening description of exercise set 6, and the names used in the code for the first question.

The code should be fine, but i have renamed some coefficients between the math and the code. So, with math notation on the left hand side, and code notation on the RHS:

gamma_0 = gamma
delta_0 = Pi
alpha_0 = alpha
beta_0 = delta

In ex. 6.1.4 you are asked to compute the _ideal_ instrument. In my math notation this would be z\*delta_0, while in my code notation it would be z\*Pi. 

I am sorry for the confusion this might cause, i was rearranging equations as i wrote the exercises.
