### ISSUE TITLE
Meter based system

### ISSUE THREAD

**Issue by PhilipChristiansen1** [Kristianuruplarsen/sdseml_online_exercises#99]
Hi Kristian,

How do I know if a system is meter-based or not?

gdp.read_file(url).crs = "EPSG:3035"  is one option, but how to know if this is meter-based?

Best,
Philip

**Comment by kristianolesenlarsen** [comment]
My best advice is that you do so by looking through _a lot_ of poorly written documentation and stackoverflow questions until you feel convinced about the way your CRS works. For instance searching [here](https://epsg.io/3035) reveals that epsg:3035 indeed has a unit metre.

(I am not really an expert on this stuff, perhaps there is some kind of logic to it i haven't found out about. Maybe @abjer will see this and has something to add).

**Comment by abjer** [comment]
Yes, Kristian is right. The CRS systems are all different. However, Kristian's response of epsg.io - they seem to write this in the attributes consistently.
